# Generated by Django 5.0.6 on 2024-06-28 13:57

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Aller simple', 'Aller Simple'), ('Aller retour', 'Aller-Retour')], max_length=50, verbose_name='Type de voyage')),
                ('slug', models.SlugField(blank=True, max_length=20, null=True, unique=True)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Travels',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=8, max_length=10, prefix='ANN')),
                ('title', models.CharField(max_length=150, verbose_name="Nom de l'annonce")),
                ('description', models.TextField(verbose_name="Description de l'annonce")),
                ('capacity', models.CharField(max_length=10, verbose_name='Capacité restante')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix par kilo')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('vendu', 'Vendu')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='annonceur')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.travel', verbose_name='voyage')),
            ],
            options={
                'verbose_name_plural': 'Annonces',
                'ordering': ['-id'],
            },
        ),
    ]
