# Generated by Django 5.0.6 on 2024-06-30 16:08

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='airline',
            field=models.CharField(default=1, max_length=200, verbose_name='COmpagnie aerienne'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='Flight tickets/', verbose_name="Capture billlet d'avion "),
        ),
        migrations.AddField(
            model_name='travel',
            name='flight_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annonce',
            name='aid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=8, max_length=15, prefix='ANN'),
        ),
    ]
