# Generated by Django 5.0.6 on 2024-07-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_travel_airline_travel_file_travel_flight_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='Flight tickets/', verbose_name="Capture billet d'avion "),
        ),
    ]
