# Generated by Django 5.0.6 on 2024-07-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_travel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
