# Generated by Django 5.0.6 on 2024-07-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_annonce_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
