# Generated by Django 5.0.6 on 2024-07-02 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_travel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Capacité restante'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel', to='services.travel', verbose_name='voyage'),
        ),
    ]
